#!/bin/bash
# Read a string with spaces using for loop
# Change the -site #### for CHR and WILD group
for pop in CHR WILD
do
    echo -e '###this script will produce files for PCA and MDS plot using the identified SNP list\n# maybe edit\ntarget="'$pop'"\nNB_CPU=32 #change accordingly\nREGIONS="-rf chr_list.txt" #optional\n#REGIONS="" # to remove the options to focus on a limited number of regions\n\n#prepare variables - avoid to modify\nsource /workdir/hz269/01_scripts/01_config.sh\nN_IND=$(wc -l $'$pop' | cut -d " " -f 1)\nMIN_IND=$(($N_IND*7/10))\n\necho "Ouput can be used for depth evaluation with all individuals listed in "$'$pop'\necho "keep loci with at leat one read for n individuals = "$MIN_IND", which is 70% of total "$N_IND" individuals"\necho "filter on allele frequency = "$MIN_MAF\n\n/programs/angsd_20180926/angsd/angsd -P $NB_CPU -doMaf 1 -dosaf 1 -GL 1 -doGlf 2 -minMaf 0.05 -doMajorMinor 3 -doIBS 1 -makeMatrix 1 -doCov 1 -anc $ANC -b $'$pop' -sites ALL_sites_all_maf0.05_pctind0.7_maxdepth3dv_snplist_4col_cv30 -out "/workdir/hz269/05_saf_maf_by_pop/"$target"_maf"$MIN_MAF"_pctind"$PERCENT_IND"_cv30_noinvers"' >> formal/'05_saf_maf_by_pop_'$pop'_cv30_noinvers.sh'
    echo -e '###this script will produce files for PCA and MDS plot using the identified SNP list\n# maybe edit\ntarget="'$pop'"\nNB_CPU=32 #change accordingly\nREGIONS="-rf chr_list.txt" #optional\n#REGIONS="" # to remove the options to focus on a limited number of regions\n\n#prepare variables - avoid to modify\nsource /workdir/hz269/01_scripts/01_config.sh\nN_IND=$(wc -l $'$pop' | cut -d " " -f 1)\nMIN_IND=$(($N_IND*7/10))\n\necho "Ouput can be used for depth evaluation with all individuals listed in "$'$pop'\necho "keep loci with at leat one read for n individuals = "$MIN_IND", which is 70% of total "$N_IND" individuals"\necho "filter on allele frequency = "$MIN_MAF\n\n/programs/angsd_20180926/angsd/angsd -P $NB_CPU -doMaf 1 -dosaf 1 -GL 1 -doGlf 2 -minMaf 0.05 -doMajorMinor 3 -doIBS 1 -makeMatrix 1 -doCov 1 -anc $ANC -b $'$pop' -out "/workdir/hz269/05_saf_maf_by_pop/"$target"_maf"$MIN_MAF"_pctind"$PERCENT_IND"_cv30O_withinvers"' >> formal/'05_saf_maf_by_pop_'$pop'_cv30_withinvers.sh'
done

