library("ggplot2")
library("cowplot")
library("ggrepel")
library("scales")
library("MASS")
library(export)
library("viridis")
library(wesanderson)
setwd("~/Dropbox/Mac/Documents/HG/DelBay_final/05_saf_maf_by_pop")
source("individual_pca_functions.R")
# for color palettes see https://r-charts.com/color-palettes/#discrete > paletteer_d("ggthemes::Hue_Circle")

PCoA <- function(dist_matrix, ind_label, pop_label, k, x_axis, y_axis, show.point=T, show.label=T, show.ellipse=T, show.line=T, alpha=0.5, index_exclude=vector())
{
    ## This function takes a pairwise distance matrix and performs PCoA
    # dist_matrix: a square distance matrix generated by most pca softwares
    # ind_label: a vector in the same order and length as dist_matrix; it contains the individual labels of the individuals represented in the covariance matrix
    # pop_label: a vector in the same order and length as dist_matrix; it contains the population labels of the individuals represented in the covariance matrix
    # x_axis: an integer that determines which principal component to plot on the x axis
    # y_axis: an integer that determines which principal component to plot on the y axis
    # show.point: whether to show individual points
    # show.label: whether to show population labels
    # show.ellipse: whether to show population-specific ellipses
    # show.line: whether to show lines connecting population means with each individual point
    # alpha: the transparency of ellipses
    # index_exclude: the indices of individuals to exclude from the analysis
    
    index_include <- setdiff(seq_along(ind_label), index_exclude)
    m <- as.matrix(read.table(dist_matrix))
    m[is.na(m)]<- median(m, na.rm = T)
    m <- m[index_include, index_include] ## Remove 4SJH, four 3Ps individuals, and contaminated ones
    mds <- cmdscale(as.dist(m), k=k)
    mds <- as.data.frame(mds)
    colnames(mds) <- paste0("dist_", 1:k)
    mds <- cbind(ind_label[index_include], pop_label[index_include], mds)
    colnames(mds)[1:2]<-c("individual", "population")
    eigen_value <- cmdscale(as.dist(m), k=k, eig = T)$eig
    var_explained <- round(eigen_value/sum(eigen_value)*100, 2)
    assign("pcoa_table", mds, .GlobalEnv)
    assign("var_explained", var_explained, .GlobalEnv)
    # cbPalette <- c("#E6E6FA", "#ADD8E6", "#87CEFA", "#B0C4DE", "#5F9EA0", "#6495ED", 
    #                "#ffa600", "#ffa600", "#ffa600",
    #                "#bd5bff", "#bd5bff", "#bd5bff",
    #                "#f84945", "#f84945", "#f84945",
    #                "#f38bff", "#f38bff", "#f38bff")
    # cbPalette <- c("#E6E6FA", "#ADD8E6", "#87CEFA", "#B0C4DE", "#5F9EA0", "#C0C0C0", "#778899", "#6495ED",
    #                "#ffa600", "#ffa600", "#ffa600",
    #                "#bd5bff", "#bd5bff", "#bd5bff",
    #                "#f84945", "#f84945", "#f84945",
    #                "#f38bff", "#f38bff", "#f38bff")
    cbPalette <- c( "#ffa08e", "#8ee3f4") # code for challenges
    #cbPalette <- c("#A71B4B", "#E97302", "#EAC728", "#0BC0B3", "#4461A8", "#F5191C", "#7A7A7A")
    #cbPalette = wes_palette("Zissou1", 18, type = "continuous")
    #idx_in_range = mds$dist_1> 2 & mds$dist_2 > 2
    #pop_list <- c("18_ARN", "18_COH", "18_HC", "18_NB", "18_C", "18_SR", "19_ARN", "19_COH", "19_HC", "19_NB", "19_SR", "19_Sur", "19_Ref", "20_Ref", "20_Sur", "21_ARN", "21_BEN", "21_BS", "21_COH", "21_C1", "21_C2", "21_HC", "21_NAN", "21_NB", "21_SR", "21_C", "21_spat_ARN", "21_spat_HC", "21_spat_Nan")
    #pop_list <- c("18_adult", "19_adult", "21_adult", "19_challenge", "20_challenge", "21_spat", 
    #              "18_adult_C1", "19_challenge_C1", "21_adult_C1", 
    #              "18_adult_C2", "19_challenge_C2", "21_adult_C2", 
    #              "20_challenge1_C3", "20_chalelnge2_C3", "21_adult_C3", 
    #              "20_challenge1_C4", "20_chalelnge2_C4",  "21_adult_C4")
    # pop_list <- c("18_adult", "19_adult", "21_adult", "19_Sur", "19_Ref","20_Sur", "20_Ref", "21_spat",
    #               "18_adult_C1", "19_challenge_C1", "21_adult_C1",
    #               "18_adult_C2", "19_challenge_C2", "21_adult_C2",
    #               "20_challenge1_C3", "20_chalelnge2_C3", "21_adult_C3",
    #               "20_challenge1_C4", "20_chalelnge2_C4",  "21_adult_C4")
    pop_list <- c("20_Sur", "20_Ref")
    PCoA_plot<-ggplot(data=mds[,], aes(x=mds[,x_axis+2], y=mds[,y_axis+2], color=population,label=population, shape=population)) + 
        
        #scale_shape_manual(values = c(rep(c(15,16,17,18),2), 15), breaks=c("CL", "CLP", "CS19", "CS", "HC", "HC_VA","HI","SL","SM")) + ## @HG changed the name for your own plots
        #scale_colour_manual(values=cbPalette, breaks=c("CL", "CLP", "CS19", "CS", "HC", "HC_VA","HI","SL","SM"))+ ## @HG changed the name for your own plots
        #scale_shape_manual(values = c(rep(c(15,16,17,18),7), 15), breaks=c("HC", "ARN", "COH", "SR", "NB", "CHR19", "REF19")) + ## @HG changed the name for your own plots
        #scale_colour_manual(values=cbPalette, breaks=c("HC", "ARN", "COH", "SR", "NB", "CHR19", "REF19"))+ ## @HG changed the name for your own plots
        scale_shape_manual(values = c(rep(c(15,16,17,18),7), 15), breaks=pop_list) +
        scale_colour_manual(values=cbPalette, breaks=pop_list)+
        #geom_text_repel(data=mds, aes_string(x=mds[,x_axis+2], y=mds[,y_axis+2]), label=mds$individual, size=3, nudge_x = 0.001, nudge_y = 0.001)+ # @HG label the individuals
        #geom_point(size=2, alpha = 1, aes(colour = factor(population)))+
        geom_enterotype(alpha=alpha, show.point=show.point, show.label=show.label, show.ellipse=show.ellipse, show.line=show.line) +
        theme_cowplot() +
        theme(
            axis.text.x = element_blank(),
            axis.text.y = element_blank()
        ) +
        xlab(paste0("PCo", x_axis, "(",var_explained[x_axis],"%)")) +
        ylab(paste0("PCo", y_axis ,"(",var_explained[y_axis],"%)"))
    print(PCoA_plot)
}


file = 'Challenge_20.txt' 
challenge_20 = read.delim(file, header = TRUE, sep='\t')

tiff(paste(file,"jpg", sep="."), units="in", width=7, height=6, res=300)
PCoA(dist_matrix = "Challenge_20_all_minq20_minmq30_CV30_masked.ibsMat",
     ind_label = challenge_20$ind,
     pop_label = challenge_20$pop,
     x_axis = 1,
     y_axis = 2,
     k = 3,
     show.point = T,
     show.label = F,
     show.ellipse = T,
     show.line = T,
     alpha = 0.01,
)
dev.off()
graph2ppt(file="PCA_challenge.pptx", width=10, height=8) 

file = 'Challenge_19.txt' 
challenge_20 = read.delim(file, header = TRUE, sep='\t')

tiff(paste(file,"jpg", sep="."), units="in", width=7, height=6, res=300)
PCoA(dist_matrix = "Challenge_20_all_minq20_minmq30_CV30_masked.ibsMat",
     ind_label = challenge_20$ind,
     pop_label = challenge_20$pop,
     x_axis = 1,
     y_axis = 2,
     k = 3,
     show.point = T,
     show.label = F,
     show.ellipse = T,
     show.line = T,
     alpha = 0.01,
)
dev.off()
graph2ppt(file="PCA_challenge.pptx", width=10, height=8) 

