library("ggplot2")
library("cowplot")
library("ggrepel")
library("scales")
library("MASS")
library(export)
library("viridis")
library(wesanderson)

#############################################
# PCA for LD-pruned SNPs -- control samples #
#############################################

setwd("~/Dropbox/Mac/Documents/HG/DelBay_final/10_prune_pca_mds")
source("individual_pca_functions.R")

PCA <- function(cov_matrix, ind_label, pop_label, x_axis, y_axis, show.point=T, show.label=T, show.ellipse=T, show.line=T, alpha=0, index_exclude=vector())
{
    ## This function takes a covariance matrix and performs PCA. 
    # cov_matrix: a square covariance matrix generated by most pca softwares
    # ind_label: a vector in the same order and length as cov_matrix; it contains the individual labels of the individuals represented in the covariance matrix
    # pop_label: a vector in the same order and length as cov_matrix; it contains the population labels of the individuals represented in the covariance matrix
    # x_axis: an integer that determines which principal component to plot on the x axis
    # y_axis: an integer that determines which principal component to plot on the y axis
    # show.point: whether to show individual points
    # show.label: whether to show population labels
    # show.ellipse: whether to show population-specific ellipses
    # show.line: whether to show lines connecting population means with each individual point
    # alpha: the transparency of ellipses
    # index_exclude: the indices of individuals to exclude from the analysis
    index_include <- setdiff(seq_along(ind_label), index_exclude)
    #m <- as.matrix(cov_matrix)
    m <- as.matrix(read.table(cov_matrix))
    m[is.na(m)]<- median(m, na.rm = T)
    m<-m[index_include, index_include] ## Remove 4SJH, four 3Ps individuals, and contaminated ones
    e <- eigen(m)
    e_value<-e$values
    x_variance<-e_value[x_axis]/sum(e_value)*100
    y_variance<-e_value[y_axis]/sum(e_value)*100
    e <- as.data.frame(e$vectors)
    e <- cbind(ind_label[index_include], pop_label[index_include], e) ## with the above individuals removed
    #colnames(e)[3:331]<-paste0("PC",1:329)
    colnames(e)[3:(dim(e)[1])]<-paste0("PC",1:(dim(e)[1]-2)) ## with the above individuals removed
    colnames(e)[1:2]<-c("individual", "population")
    assign("pca_table", e, .GlobalEnv)
    cbPalette <- wes_palette("Zissou1", 4, type = "continuous")
    pop_list <- c("Control_1", "Control_2", "Control_3", "Control_4")
    # pop_list <- c("18_HC", "18_ARN", "18_COH", "18_SR", "18_NB", "19_HC", "19_ARN", "19_COH", "19_SR", "19_NB", "21_HC", "21_ARN", "21_COH", "21_SR", "21_BS", "21_BEN", "21_NAN", "21_NB")
    
    PCA_plot<-ggplot(data=e[,],aes(x=e[,x_axis+2], y=e[,y_axis+2], color=population,label=population, shape=population)) + 
        scale_shape_manual(values = c(rep(c(15,16,17,18),7), 15), breaks=pop_list) +
        scale_colour_manual(values=cbPalette, breaks=pop_list)+
        #geom_enterotype(alpha=alpha, show.point=show.point, show.label=show.label, show.ellipse=show.ellipse, show.line=show.line) +
        #geom_text_repel()+
        theme_cowplot() +
        geom_point(size = 6, alpha = 0.5)+ # @HG change the point size
        theme(
            axis.text.x = element_blank(),
            axis.text.y = element_blank()
        ) +
        xlab(paste0("PC", x_axis, "(",round(x_variance,2),"%)")) +
        ylab(paste0("PC", y_axis ,"(",round(y_variance,2),"%)")) 
    # function to plot the labels note for population with one individual it will report warning message
    # PCA_plot<-ggplot(data=e[,],aes(x=e[,x_axis+2], y=e[,y_axis+2], color=population,label=individual, shape=population)) + 
    #   geom_enterotype(alpha=alpha, show.point=show.point, show.label=show.label, show.ellipse=show.ellipse, show.line=show.line) +
    #   scale_shape_manual(values = c(rep(c(15,16,17,18),7), 15, 16)) +
    #   geom_text_repel()+
    #   theme_cowplot() +
    #   theme(
    #     axis.text.x = element_blank(),
    #     axis.text.y = element_blank()
    #   ) +
    #   xlab(paste0("PC", x_axis, "(",round(x_variance,2),"%)")) +
    #   ylab(paste0("PC", y_axis ,"(",round(y_variance,2),"%)")) 
    print(PCA_plot)
}

# control groups
file = 'All_control_info.txt' 
all_label = read.delim(file, header = TRUE, sep='\t')
all_label$pop <- factor(all_label$pop, levels = c("Control_1", "Control_2", "Control_3", "Control_4"))
cbPalette <- wes_palette("Zissou1", 4, type = "continuous")

PCA(cov_matrix = "Control_maf0.05_minmapq30_minq20_CV30_masked.covMat",
    ind_label = all_label$ind,
    pop_label = all_label$pop,
    x_axis = 1,
    y_axis = 2,
    show.point = T,
    show.label = F,
    show.ellipse = F,
    show.line = F,
    alpha = 0.3,
)
graph2ppt(file="Figure_S1", width=8, height=6)

##########################################
# PCA for LD-pruned SNPs -- 1342 samples #
##########################################

setwd("~/Dropbox/Mac/Documents/HG/DelBay_final/10_prune_pca_mds")
source("individual_pca_functions.R")

PCA <- function(cov_matrix, ind_label, pop_label, x_axis, y_axis, show.point=T, show.label=T, show.ellipse=T, show.line=T, alpha=0, index_exclude=vector())
{
    ## This function takes a covariance matrix and performs PCA. 
    # cov_matrix: a square covariance matrix generated by most pca softwares
    # ind_label: a vector in the same order and length as cov_matrix; it contains the individual labels of the individuals represented in the covariance matrix
    # pop_label: a vector in the same order and length as cov_matrix; it contains the population labels of the individuals represented in the covariance matrix
    # x_axis: an integer that determines which principal component to plot on the x axis
    # y_axis: an integer that determines which principal component to plot on the y axis
    # show.point: whether to show individual points
    # show.label: whether to show population labels
    # show.ellipse: whether to show population-specific ellipses
    # show.line: whether to show lines connecting population means with each individual point
    # alpha: the transparency of ellipses
    # index_exclude: the indices of individuals to exclude from the analysis
    index_include <- setdiff(seq_along(ind_label), index_exclude)
    #m <- as.matrix(cov_matrix)
    m <- as.matrix(read.table(cov_matrix))
    m[is.na(m)]<- median(m, na.rm = T)
    m<-m[index_include, index_include] ## Remove 4SJH, four 3Ps individuals, and contaminated ones
    e <- eigen(m)
    e_value<-e$values
    x_variance<-e_value[x_axis]/sum(e_value)*100
    y_variance<-e_value[y_axis]/sum(e_value)*100
    e <- as.data.frame(e$vectors)
    e <- cbind(ind_label[index_include], pop_label[index_include], e) ## with the above individuals removed
    #colnames(e)[3:331]<-paste0("PC",1:329)
    colnames(e)[3:(dim(e)[1])]<-paste0("PC",1:(dim(e)[1]-2)) ## with the above individuals removed
    colnames(e)[1:2]<-c("individual", "population")
    assign("pca_table", e, .GlobalEnv)
    cbPalette <- wes_palette("Zissou1", 25, type = "continuous")
    pop_list <- c("18_HC","18_ARN","18_COH","18_SR","18_NB",
                  "19_HC","19_ARN","19_COH","19_SR","19_NB",
                  "21_HC","21_ARN","21_COH","21_SR","21_BS","21_BEN","21_NAN","21_NB",
                  "19_Sur","19_Ref","20_Sur","20_Ref","20A","20B","20C")
    PCA_plot<-ggplot(data=e[,],aes(x=e[,x_axis+2], y=e[,y_axis+2], color=population,label=population, shape=population)) + 
        scale_shape_manual(values = c(rep(c(15,16,17,18),7), 15), breaks=pop_list) +
        scale_colour_manual(values=cbPalette, breaks=pop_list)+
        geom_enterotype(alpha=alpha, show.point=show.point, show.label=show.label, show.ellipse=show.ellipse, show.line=show.line) +
        #geom_text_repel()+
        theme_cowplot() +
        #geom_point(size = 6, alpha = 0.5)+ # @HG change the point size
        theme(
            axis.text.x = element_blank(),
            axis.text.y = element_blank()
        ) +
        xlab(paste0("PC", x_axis, "(",round(x_variance,2),"%)")) +
        ylab(paste0("PC", y_axis ,"(",round(y_variance,2),"%)")) 
    # function to plot the labels note for population with one individual it will report warning message
    # PCA_plot<-ggplot(data=e[,],aes(x=e[,x_axis+2], y=e[,y_axis+2], color=population,label=individual, shape=population)) + 
    #   geom_enterotype(alpha=alpha, show.point=show.point, show.label=show.label, show.ellipse=show.ellipse, show.line=show.line) +
    #   scale_shape_manual(values = c(rep(c(15,16,17,18),7), 15, 16)) +
    #   geom_text_repel()+
    #   theme_cowplot() +
    #   theme(
    #     axis.text.x = element_blank(),
    #     axis.text.y = element_blank()
    #   ) +
    #   xlab(paste0("PC", x_axis, "(",round(x_variance,2),"%)")) +
    #   ylab(paste0("PC", y_axis ,"(",round(y_variance,2),"%)")) 
    print(PCA_plot)
}

# control groups
file = 'All_1342_info.txt' 
all_label = read.delim(file, header = TRUE, sep='\t')
all_label$pop <- factor(all_label$pop, levels = c("18_HC","18_ARN","18_COH","18_SR","18_NB",
                                                  "19_HC","19_ARN","19_COH","19_SR","19_NB",
                                                  "21_HC","21_ARN","21_COH","21_SR","21_BS","21_BEN","21_NAN","21_NB",
                                                  "19_Sur","19_Ref","20_Sur","20_Ref","20A","20B","20C"))
cbPalette <- wes_palette("Zissou1", 25, type = "continuous")

p1 <- PCA(cov_matrix = "All_pca_1342_all_minq20_minmq30_CV30_masked_chr1.covMat",
          ind_label = all_label$ind,
          pop_label = all_label$pop,
          x_axis = 1,
          y_axis = 2,
          show.point = T,
          show.label = F,
          show.ellipse = F,
          show.line = F,
          alpha = 0.3,
)

p2 <- PCA(cov_matrix = "All_pca_1342_all_minq20_minmq30_CV30_masked_chr2.covMat",
          ind_label = all_label$ind,
          pop_label = all_label$pop,
          x_axis = 1,
          y_axis = 2,
          show.point = T,
          show.label = F,
          show.ellipse = F,
          show.line = F,
          alpha = 0.3,
)

p3 <- PCA(cov_matrix = "All_pca_1342_all_minq20_minmq30_CV30_masked_chr3.covMat",
          ind_label = all_label$ind,
          pop_label = all_label$pop,
          x_axis = 1,
          y_axis = 2,
          show.point = T,
          show.label = F,
          show.ellipse = F,
          show.line = F,
          alpha = 0.3,
)

p4 <- PCA(cov_matrix = "All_pca_1342_all_minq20_minmq30_CV30_masked_chr4.covMat",
          ind_label = all_label$ind,
          pop_label = all_label$pop,
          x_axis = 1,
          y_axis = 2,
          show.point = T,
          show.label = F,
          show.ellipse = F,
          show.line = F,
          alpha = 0.3,
)

p5 <- PCA(cov_matrix = "All_pca_1342_all_minq20_minmq30_CV30_masked_chr5.covMat",
          ind_label = all_label$ind,
          pop_label = all_label$pop,
          x_axis = 1,
          y_axis = 2,
          show.point = T,
          show.label = F,
          show.ellipse = F,
          show.line = F,
          alpha = 0.3,
)

p6 <- PCA(cov_matrix = "All_pca_1342_all_minq20_minmq30_CV30_masked_chr6.covMat",
          ind_label = all_label$ind,
          pop_label = all_label$pop,
          x_axis = 1,
          y_axis = 2,
          show.point = T,
          show.label = F,
          show.ellipse = F,
          show.line = F,
          alpha = 0.3,
)

p7 <- PCA(cov_matrix = "All_pca_1342_all_minq20_minmq30_CV30_masked_chr7.covMat",
    ind_label = all_label$ind,
    pop_label = all_label$pop,
    x_axis = 1,
    y_axis = 2,
    show.point = T,
    show.label = F,
    show.ellipse = F,
    show.line = F,
    alpha = 0.3,
)

p8 <- PCA(cov_matrix = "All_pca_1342_all_minq20_minmq30_CV30_masked_chr8.covMat",
          ind_label = all_label$ind,
          pop_label = all_label$pop,
          x_axis = 1,
          y_axis = 2,
          show.point = T,
          show.label = F,
          show.ellipse = F,
          show.line = F,
          alpha = 0.3,
)

p9 <- PCA(cov_matrix = "All_pca_1342_all_minq20_minmq30_CV30_masked_chr9.covMat",
          ind_label = all_label$ind,
          pop_label = all_label$pop,
          x_axis = 1,
          y_axis = 2,
          show.point = T,
          show.label = F,
          show.ellipse = F,
          show.line = F,
          alpha = 0.01,
)

p10 <- PCA(cov_matrix = "All_pca_1342_all_minq20_minmq30_CV30_masked_chr10.covMat",
          ind_label = all_label$ind,
          pop_label = all_label$pop,
          x_axis = 1,
          y_axis = 2,
          show.point = T,
          show.label = F,
          show.ellipse = F,
          show.line = F,
          alpha = 0.01,
)

library(patchwork)
p1+p2+p3+p4+p5+p6+p7+p8+p9+p10+ plot_layout(guides="collect")
graph2ppt(file="Figure_S2", width=14, height=10)

##############################



































setwd("~/Dropbox/Mac/Documents/HG/DelBay_final/03_PCA_MDS")
source("individual_pca_functions.R")
# for color palettes see https://r-charts.com/color-palettes/#discrete > paletteer_d("ggthemes::Hue_Circle")

file = 'All_wild_info.txt' 
all_label = read.delim(file, header = TRUE, sep='\t')
all_label$pop <- factor(all_label$pop, levels = c("18_HC", "18_ARN", "18_COH", "18_SR", "18_NB", "19_HC", "19_ARN", "19_COH", "19_SR", "19_NB", "21_HC", "21_ARN", "21_COH", "21_SR", "21_BS", "21_BEN", "21_NAN", "21_NB"))
cbPalette <- wes_palette("Zissou1", 18, type = "continuous")

PCoA <- function(dist_matrix, ind_label, pop_label, k, x_axis, y_axis, show.point=T, show.label=T, show.ellipse=T, show.line=T, alpha=0.5, index_exclude=vector())
{
    ## This function takes a pairwise distance matrix and performs PCoA
    # dist_matrix: a square distance matrix generated by most pca softwares
    # ind_label: a vector in the same order and length as dist_matrix; it contains the individual labels of the individuals represented in the covariance matrix
    # pop_label: a vector in the same order and length as dist_matrix; it contains the population labels of the individuals represented in the covariance matrix
    # x_axis: an integer that determines which principal component to plot on the x axis
    # y_axis: an integer that determines which principal component to plot on the y axis
    # show.point: whether to show individual points
    # show.label: whether to show population labels
    # show.ellipse: whether to show population-specific ellipses
    # show.line: whether to show lines connecting population means with each individual point
    # alpha: the transparency of ellipses
    # index_exclude: the indices of individuals to exclude from the analysis
    
    index_include <- setdiff(seq_along(ind_label), index_exclude)
    m <- as.matrix(read.table(dist_matrix))
    m[is.na(m)]<- median(m, na.rm = T)
    m <- m[index_include, index_include] ## Remove 4SJH, four 3Ps individuals, and contaminated ones
    mds <- cmdscale(as.dist(m), k=k)
    mds <- as.data.frame(mds)
    colnames(mds) <- paste0("dist_", 1:k)
    mds <- cbind(ind_label[index_include], pop_label[index_include], mds)
    colnames(mds)[1:2]<-c("individual", "population")
    eigen_value <- cmdscale(as.dist(m), k=k, eig = T)$eig
    var_explained <- round(eigen_value/sum(eigen_value)*100, 2)
    assign("pcoa_table", mds, .GlobalEnv)
    assign("var_explained", var_explained, .GlobalEnv)
    cbPalette <- wes_palette("Zissou1", 18, type = "continuous")
    # cbPalette <- c("#E6E6FA", "#ADD8E6", "#87CEFA", "#B0C4DE", "#5F9EA0", "#6495ED", 
    #                "#ffa600", "#ffa600", "#ffa600",
    #                "#bd5bff", "#bd5bff", "#bd5bff",
    #                "#f84945", "#f84945", "#f84945",
    #                "#f38bff", "#f38bff", "#f38bff")
    #cbPalette <- c("#E6E6FA", "#ADD8E6", "#87CEFA", "#B0C4DE", "#5F9EA0", "#C0C0C0", "#778899", "#6495ED",
    #               "#ffa600", "#ffa600", "#ffa600",
    #               "#bd5bff", "#bd5bff", "#bd5bff",
    #               "#f84945", "#f84945", "#f84945",
    #               "#f38bff", "#f38bff", "#f38bff")
    #cbPalette <- c("#E6E6FA", "#f84945", "#87CEFA", "#f38bff") # code for challenges
    #cbPalette <- c("#A71B4B", "#E97302", "#EAC728", "#0BC0B3", "#4461A8", "#F5191C", "#7A7A7A")
    #cbPalette = wes_palette("Zissou1", 18, type = "continuous")
    #idx_in_range = mds$dist_1> 2 & mds$dist_2 > 2
    pop_list <- c("18_HC", "18_ARN", "18_COH", "18_SR", "18_NB", "19_HC", "19_ARN", "19_COH", "19_SR", "19_NB", "21_HC", "21_ARN", "21_COH", "21_SR", "21_BS", "21_BEN", "21_NAN", "21_NB")
    #pop_list <- c("18_adult", "19_adult", "21_adult", "19_challenge", "20_challenge", "21_spat", 
    #              "18_adult_C1", "19_challenge_C1", "21_adult_C1", 
    #              "18_adult_C2", "19_challenge_C2", "21_adult_C2", 
    #              "20_challenge1_C3", "20_chalelnge2_C3", "21_adult_C3", 
    #              "20_challenge1_C4", "20_chalelnge2_C4",  "21_adult_C4")
    #pop_list <- c("18_adult", "19_adult", "21_adult", "19_Sur", "19_Ref","20_Sur", "20_Ref", "21_spat",
    #              "18_adult_C1", "19_challenge_C1", "21_adult_C1",
    #              "18_adult_C2", "19_challenge_C2", "21_adult_C2",
    #              "20_challenge1_C3", "20_chalelnge2_C3", "21_adult_C3",
    #              "20_challenge1_C4", "20_chalelnge2_C4",  "21_adult_C4")
    #pop_list <- c("19_Sur", "19_Ref","20_Sur", "20_Ref")
    PCoA_plot<-ggplot(data=mds[,], aes(x=mds[,x_axis+2], y=mds[,y_axis+2], color=population,label=population, shape=population)) + 
        
        #scale_shape_manual(values = c(rep(c(15,16,17,18),2), 15), breaks=c("CL", "CLP", "CS19", "CS", "HC", "HC_VA","HI","SL","SM")) + ## @HG changed the name for your own plots
        #scale_colour_manual(values=cbPalette, breaks=c("CL", "CLP", "CS19", "CS", "HC", "HC_VA","HI","SL","SM"))+ ## @HG changed the name for your own plots
        #scale_shape_manual(values = c(rep(c(15,16,17,18),7), 15), breaks=c("HC", "ARN", "COH", "SR", "NB", "CHR19", "REF19")) + ## @HG changed the name for your own plots
        #scale_colour_manual(values=cbPalette, breaks=c("HC", "ARN", "COH", "SR", "NB", "CHR19", "REF19"))+ ## @HG changed the name for your own plots
        scale_shape_manual(values = c(rep(c(15,16,17,18),7), 15), breaks=pop_list) +
        scale_colour_manual(values=cbPalette, breaks=pop_list)+
        #geom_text_repel(data=mds, aes_string(x=mds[,x_axis+2], y=mds[,y_axis+2]), label=mds$individual, size=3, nudge_x = 0.001, nudge_y = 0.001)+ # @HG label the individuals
        #geom_point(size=2, alpha = 1, aes(colour = factor(population)))+
        geom_enterotype(alpha=alpha, show.point=show.point, show.label=show.label, show.ellipse=show.ellipse, show.line=show.line) +
        theme_cowplot() +
        theme(
            axis.text.x = element_blank(),
            axis.text.y = element_blank()
        ) +
        xlab(paste0("PCo", x_axis, "(",var_explained[x_axis],"%)")) +
        ylab(paste0("PCo", y_axis ,"(",var_explained[y_axis],"%)"))
    print(PCoA_plot)
}





PCoA(dist_matrix = "All_wild_maf0.05_minmapq30_minq20_pctind0.7_CV30_masked.ibsMat",
     ind_label = all_label$ind,
     pop_label = all_label$pop,
     x_axis = 1,
     y_axis = 2,
     k = 5,
     show.point = T,
     show.label = F,
     show.ellipse = F,
     show.line = F,
     alpha = 2
)
graph2ppt(file="All_wild_MDS_chr10_prune", width=12, height=10)

PCA(cov_matrix = "All_wild_maf0.05_minmapq30_minq20_pctind0.7_CV30_masked.covMat",
    ind_label = all_label$ind,
    pop_label = all_label$pop,
    x_axis = 1,
    y_axis = 2,
    show.point = T,
    show.label = F,
    show.ellipse = T,
    show.line = F,
    alpha = 0.01,
)
graph2ppt(file="All_wild_PCA_chr10_prune", width=12, height=10) 


PCA(cov_matrix = "All_wild_all_minq20_minmq30_CV30_masked_chr9.covMat",
    ind_label = all_label$ind,
    pop_label = all_label$pop,
    x_axis = 1,
    y_axis = 2,
    show.point = T,
    show.label = F,
    show.ellipse = T,
    show.line = F,
    alpha = 0.01,
    index_exclude=c(184,185, 501, 521, 842, 843, 125,126,540, 666)
)

graph2ppt(file="All_wild_PCA_PC3-4", width=8, height=6)

PCoA(dist_matrix = "All_wild_maf0.05_minmapq30_minq20_pctind0.7_CV30_masked.ibsMat",
     ind_label = all_label$ind,
     pop_label = all_label$pop,
     x_axis = 2,
     y_axis = 3,
     k = 5,
     show.point = T,
     show.label = F,
     show.ellipse = T,
     show.line = F,
     alpha = 0.01,
    index_exclude=c(184,185, 501, 521, 842, 843, 125,126,540, 666)
)

graph2ppt(file="All_wild_MDS", width=12, height=10)
 


DAPC(n=50,
     x_axis = 1,
     y_axis = 2,
     show.point = T,
     show.label = F,
     show.ellipse = F,
     show.line = F,
)


#####################
# chr1-10 prune snp #
#####################
setwd("~/Dropbox/Mac/Documents/HG/DelBay_final/10_prune_pca_mds")
for (i in c(1:10)){
    fname = paste0("All_wild_all_minq20_minmq30_CV30_masked_chr", i, ".covMat")
    PCA(cov_matrix = fname,
        ind_label = all_label$ind,
        pop_label = all_label$pop,
        x_axis = 1,
        y_axis = 2,
        show.point = T,
        show.label = F,
        show.ellipse = T,
        show.line = F,
        alpha = 0.01,
    )
    graph2ppt(file=paste0("All_wild_chr", i), width=8, height=6)
}




