# sfs is generated by 
# module load angsd/0.931
# BASE_DIR='/scratch/hzz0024/DelBay19_Sep/05_saf_maf_by_pop/SFS/'
# for POP in {CH,REF,HC,ARN,COH,SR,NB}; do
# echo $POP' sfs starts'
# /tools/angsd-0.931/misc/realSFS \
# $BASE_DIR$POP'_maf0.05_pctind0.7_cv30.saf.idx' \
# -P 16 -fold 1 \
# > $BASE_DIR$POP'.sfs'
# done

setwd("~/Documents/Ryan_workplace/DelBay19_SFS")
