library("ggplot2")
library("cowplot")
library("ggrepel")
library("scales")
library("MASS")
library(export)
setwd("~/Dropbox/Mac/Documents/HG/CVreseq_wild_angsd/03_MDS_PCA/ibsmat/")
source("individual_pca_functions.R")
# for color palettes see https://r-charts.com/color-palettes/#discrete > paletteer_d("ggthemes::Hue_Circle")
file = 'All_92_info.txt' 
all_label = read.delim(file, header = TRUE, sep='\t')

PCoA <- function(dist_matrix, ind_label, pop_label, k, x_axis, y_axis, show.point=T, show.label=T, show.ellipse=T, show.line=T, alpha=0, index_exclude=vector())
{
    ## This function takes a pairwise distance matrix and performs PCoA
    # dist_matrix: a square distance matrix generated by most pca softwares
    # ind_label: a vector in the same order and length as dist_matrix; it contains the individual labels of the individuals represented in the covariance matrix
    # pop_label: a vector in the same order and length as dist_matrix; it contains the population labels of the individuals represented in the covariance matrix
    # x_axis: an integer that determines which principal component to plot on the x axis
    # y_axis: an integer that determines which principal component to plot on the y axis
    # show.point: whether to show individual points
    # show.label: whether to show population labels
    # show.ellipse: whether to show population-specific ellipses
    # show.line: whether to show lines connecting population means with each individual point
    # alpha: the transparency of ellipses
    # index_exclude: the indices of individuals to exclude from the analysis
    
    index_include <- setdiff(seq_along(ind_label), index_exclude)
    m <- as.matrix(read.table(dist_matrix))
    m[is.na(m)]<- median(m, na.rm = T)
    m <- m[index_include, index_include] ## Remove 4SJH, four 3Ps individuals, and contaminated ones
    mds <- cmdscale(as.dist(m), k=k)
    mds <- as.data.frame(mds)
    colnames(mds) <- paste0("dist_", 1:k)
    mds <- cbind(ind_label[index_include], pop_label[index_include], mds)
    colnames(mds)[1:2]<-c("individual", "population")
    eigen_value <- cmdscale(as.dist(m), k=k, eig = T)$eig
    var_explained <- round(eigen_value/sum(eigen_value)*100, 2)
    assign("pcoa_table", mds, .GlobalEnv)
    assign("var_explained", var_explained, .GlobalEnv)
    
    cbPalette <- c("#000000", "#E69F00", "#56B4E9", "#009E73", "#ff0000", "#ff7878", "#D55E00", "#CC79A7", "#8FDDE7")
    idx_in_range = mds$dist_1> -1 & mds$dist_2 > -1
    
    PCoA_plot<-ggplot(data=mds[,], aes(x=mds[,x_axis+2], y=mds[,y_axis+2], color=population,label=population, shape=population)) + 
        
        #scale_shape_manual(values = c(rep(c(15,16,17,18),2), 15), breaks=c("CL", "CLP", "CS19", "CS", "HC", "HC_VA","HI","SL","SM")) + ## @HG changed the name for your own plots
        #scale_colour_manual(values=cbPalette, breaks=c("CL", "CLP", "CS19", "CS", "HC", "HC_VA","HI","SL","SM"))+ ## @HG changed the name for your own plots
        
        scale_shape_manual(values = c(rep(c(15,16,17,18),2), 15), breaks=c("LM_batch1", "LM_batch2")) + ## @HG changed the name for your own plots
        scale_colour_manual(values=cbPalette, breaks=c("LM_batch1", "LM_batch2"))+ ## @HG changed the name for your own plots
        
        geom_text_repel(data=mds, aes_string(x=mds[,x_axis+2], y=mds[,y_axis+2]), label=mds$individual, size=3, nudge_x = 0.001, nudge_y = 0.001)+ # @HG label the individuals
        
        geom_enterotype(alpha=alpha, show.point=show.point, show.label=show.label, show.ellipse=show.ellipse, show.line=show.line) +
        theme_cowplot() +
        theme(
            axis.text.x = element_blank(),
            axis.text.y = element_blank()
        ) +
        xlab(paste0("PCo", x_axis, "(",var_explained[x_axis],"%)")) +
        ylab(paste0("PCo", y_axis ,"(",var_explained[y_axis],"%)"))
    print(PCoA_plot)
}

PCoA(dist_matrix = "All_maf0.05_minmapq30_minq20_pctind09_CV30_masked.ibsMat",
     ind_label = all_label$ind,
     pop_label = all_label$pop,
     x_axis = 1,
     y_axis = 2,
     k = 3,
     show.point = T,
     show.label = T,
     show.ellipse = T,
     show.line = F,
     alpha = 0.01,
     index_exclude=(38:38)
)

file = 'LM.txt' 
CLP = read.delim(file, header = TRUE, sep='\t')
tiff(paste(file,"jpg", sep="."), units="in", width=7, height=6, res=300)
PCoA(dist_matrix = "LM_6_minmapq30_minq20_CV30_masked_noinvers_shared_sites.ibsMat",
     ind_label = CLP$ind,
     pop_label = CLP$pop,
     x_axis = 1,
     y_axis = 2,
     k = 3,
     show.point = T,
     show.label = T,
     show.ellipse = T,
     show.line = T,
     alpha = 0.01,
     #index_exclude=(1:38)
)
dev.off()

file = 'CS.txt' 
CS = read.delim(file, header = TRUE, sep='\t')
tiff(paste(file,"jpg", sep="."), units="in", width=7, height=6, res=300)
PCoA(dist_matrix = "All_maf0.05_minmapq30_minq20_pctind09_CV30_masked.ibsMat",
     ind_label = CS$ind,
     pop_label = CS$pop,
     x_axis = 1,
     y_axis = 2,
     k = 2,
     show.point = T,
     show.label = T,
     show.ellipse = T,
     show.line = F,
     alpha = 0.01,
     index_exclude = c(seq(1:21), 38, seq(42,92, by=1))
)
dev.off()

file = 'HC_VA10.txt' 
CS = read.delim(file, header = TRUE, sep='\t')
tiff(paste(file,"jpg", sep="."), units="in", width=7, height=6, res=300)
PCoA(dist_matrix = "All_maf0.05_minmapq30_minq20_pctind09_CV30_masked.ibsMat",
     ind_label = CS$ind,
     pop_label = CS$pop,
     x_axis = 1,
     y_axis = 2,
     k = 2,
     show.point = T,
     show.label = T,
     show.ellipse = T,
     show.line = F,
     alpha = 0.01,
     index_exclude = c(seq(1:51), seq(62,92, by=1))
)
dev.off()

file = 'HC.txt' 
CS = read.delim(file, header = TRUE, sep='\t')
tiff(paste(file,"jpg", sep="."), units="in", width=7, height=6, res=300)
PCoA(dist_matrix = "All_maf0.05_minmapq30_minq20_pctind09_CV30_masked.ibsMat",
     ind_label = CS$ind,
     pop_label = CS$pop,
     x_axis = 1,
     y_axis = 2,
     k = 2,
     show.point = T,
     show.label = T,
     show.ellipse = T,
     show.line = F,
     alpha = 0.01,
     index_exclude = c(seq(1:41), seq(52,92, by=1))
)
dev.off()

file = 'SM.txt' 
CS = read.delim(file, header = TRUE, sep='\t')
tiff(paste(file,"jpg", sep="."), units="in", width=7, height=6, res=300)
PCoA(dist_matrix = "All_maf0.05_minmapq30_minq20_pctind09_CV30_masked.ibsMat",
     ind_label = CS$ind,
     pop_label = CS$pop,
     x_axis = 1,
     y_axis = 2,
     k = 2,
     show.point = T,
     show.label = T,
     show.ellipse = T,
     show.line = F,
     alpha = 0.01,
     index_exclude = c(seq(1:82))
)
dev.off()

file = 'HI.txt' 
CS = read.delim(file, header = TRUE, sep='\t')
tiff(paste(file,"jpg", sep="."), units="in", width=7, height=6, res=300)
PCoA(dist_matrix = "All_maf0.05_minmapq30_minq20_pctind09_CV30_masked.ibsMat",
     ind_label = CS$ind,
     pop_label = CS$pop,
     x_axis = 1,
     y_axis = 2,
     k = 2,
     show.point = T,
     show.label = T,
     show.ellipse = T,
     show.line = F,
     alpha = 0.01,
     index_exclude = c(seq(1:61), seq(77,92, by=1))
)
dev.off()
